# Profil: generisch (kein unterstütztes OS sicher erkannt)
# Konservativ: keine Proxmox-Aktionen, vorsichtig mit Härtung.
PVE_DISABLE_ENTERPRISE=false
PVE_SWITCH_NOSUB_REPO=false
PVE_DISABLE_CEPH_ENTERPRISE=false
PVE_SWITCH_CEPH_NOSUB=false
PBS_DISABLE_ENTERPRISE=false
PBS_SWITCH_NOSUB_REPO=false
