# Profile: Proxmox VE 9 (base: Debian 13 trixie)
# Repo switch + tuning active. ZFS ARC is asked interactively by default.
PVE_DISABLE_ENTERPRISE=true
PVE_SWITCH_NOSUB_REPO=true
PVE_DISABLE_CEPH_ENTERPRISE=true
PVE_SWITCH_CEPH_NOSUB=true
SWAPPINESS=10
ZFS_ARC_PROMPT=true
# On virtualization hosts chrony is often the better choice:
NTP_BACKEND="chrony"
