# Profil: Proxmox VE 9 (Basis: Debian 13 trixie)
# Repo-Umstellung + Tuning aktiv. ZFS-ARC wird per Default interaktiv erfragt.
PVE_DISABLE_ENTERPRISE=true
PVE_SWITCH_NOSUB_REPO=true
PVE_DISABLE_CEPH_ENTERPRISE=true
PVE_SWITCH_CEPH_NOSUB=true
SWAPPINESS=10
ZFS_ARC_PROMPT=true
# Auf Virtualisierungs-Hosts ist chrony oft die bessere Wahl:
NTP_BACKEND="chrony"
